const CourseList = [
    {code:"ALL", name: "ALL"},
    { code: "AED", name: "Adult Education" },
    { code: "AGR", name: "Agriculture" },
    { code: "ANA", name: "Anatomy" },
    { code: "ARC", name: "Architecture" },
    { code: "ART", name: "Art and Design" },
    { code: "BFN", name: "Banking and Finance" },
    { code: "BIO", name: "Biology" },
    { code: "BOT", name: "Botany" },
    { code: "CEM", name: "Chemical Engineering" },
    { code: "CHE", name: "Chemistry" },
    { code: "CHM", name: "Community Health" },
    { code: "CIV", name: "Civil Engineering" },
    { code: "COM", name: "Communications" },
    { code: "CPT", name: "Computer Science and Technology" },
    { code: "CRD", name: "Criminology and Security Studies" },
    { code: "CSC", name: "Computer Science" },
    { code: "CSP", name: "Cyber Security" },
    { code: "DRA", name: "Drama and Theatre Arts" },
    { code: "DTP", name: "Desktop Publishing Technology" },
    { code: "ECE", name: "Early Childhood Education" },
    { code: "ECO", name: "Economics" },
    { code: "EED", name: "Elementary Education" },
    { code: "EEE", name: "Electrical and Electronic Engineering" },
    { code: "ELE", name: "Electronics Engineering" },
    { code: "ENG", name: "English Language" },
    { code: "ENV", name: "Environmental Science" },
    { code: "ESL", name: "English as a Second Language" },
    { code: "ESM", name: "Entrepreneurship Management" },
    { code: "EST", name: "Estate Management" },
    { code: "FIS", name: "Fisheries" },
    { code: "FST", name: "Food Science and Technology" },
    { code: "FRC", name: "French"},
    { code: "GEO", name: "Geography" },
    { code: "GLT", name: "Geology and Mineral Technology" },
    { code: "GST", name: "General Studies" },
    { code: "HCM", name: "Health Care Management" },
    { code: "HIS", name: "History" },
    { code: "HMT", name: "Hospitality and Management Technology" },
    { code: "HPE", name: "Human Kinetics and Physical Education" },
    { code: "HSC", name: "Health Science" },
    { code: "ICT", name: "Information and Communications Technology" },
    { code: "IND", name: "Industrial Design" },
    { code: "INS", name: "Insurance" },
    { code: "IRM", name: "International Relations and Diplomacy" },
    { code: "ITE", name: "Industrial Technical Education" },
    { code: "LAR", name: "Landscape Architecture" },
      { code: "LAW", name: "Law" },
    { code: "LIB", name: "Library Science" },
    { code: "LIT", name: "Literature" },
    { code: "MAC", name: "Mass Communication" },
    { code: "MAR", name: "Marketing" },
    { code: "MCB", name: "Microbiology" },
    { code: "MCE", name: "Mechanical Engineering" },
    { code: "MCJ", name: "Mass Communication and Journalism" },
    { code: "MCM", name: "Mass Communication and Media Studies" },
    { code: "MEE", name: "Mechatronics Engineering" },
    { code: "MED", name: "Medicine and Surgery" },
    { code: "MLS", name: "Medical Laboratory Science"},
    { code: "MET", name: "Metallurgical Engineering" },
    { code: "MGT", name: "Management" },
    { code: "MME", name: "Materials and Metallurgical Engineering" },
    { code: "MTH", name: "Mathematics and Statistics" },
    { code: "MUS", name: "Music" },
    { code: "NSE", name: "Nursery and Elementary Education" },
    { code: "NTF", name: "Nutrition and Dietetics" },
    { code: "NUR", name: "Nursing Science" },
    { code: "PAB", name: "Public Administration and Business Studies" },
    { code: "PAM", name: "Public Administration and Management" },
    { code: "PAS", name: "Public Administration" },
    { code: "PBS", name: "Public and Business Studies" },
    { code: "PES", name: "Physical and Health Education" },
    { code: "PET", name: "Petroleum Engineering" },
    { code: "PHA", name: "Pharmacology" },
    { code: "PHS", name: "Public Health" },
    { code: "PLS", name: "Political Science" },
    { code: "POL", name: "Polymer Engineering" },
    { code: "PTM", name: "Printing Technology Management" },
    { code: "PUB", name: "Publishing and Printing Technology" },
    { code: "QSV", name: "Quantity Surveying" },
    { code: "RAS", name: "Radiography and Radiological Science" },
    { code: "RCS", name: "Rehabilitation and Counselling Studies" },
    { code: "RME", name: "Remote Sensing and Geoinformatics Engineering" },
    { code: "RST", name: "Religious Studies" },
    { code: "SCI", name: "Science" },
    { code: "SCL", name: "Soil Conservation and Land Reclamation" },
    { code: "SOC", name: "Sociology" },
    { code: "SPA", name: "Spanish" },
    { code: "SSS", name: "Social Studies" },
]

export default CourseList