import React from "react";
import Footer from "../../components/footer/Footer";
import MetaData from "../../MetaData";
import { IconHelp } from "../../assets/icons";
import styled from "styled-components";

const Help = () => {
  const freQuestions = [
    {
      question: "How do I download past question papers or course material?",
      answer: `To download past question papers or course materials, simply search the course code or title in the search bar or navigate
      to the study material page and select the course title, level, and session then allow it to load, afterwards - click on the download button
      provided at the top left corner. The papers are available in PDF
      format for easy access and offline use.`,
      ischecked: true,
    },
    {
      question: "Are the answers provided accurate?",
      answer: `Yes, the answers are carefully designed to provide accurate
      and reliable information. However, please note that some of
      these answers are generated by an AI model and may not always
      be perfect. We recommend cross-referencing the answers with
      your course material and consulting with your instructors for
      any doubts or clarifications.`,
    },
    {
      question: "How do I write a new story?",
      answer: `To write a new story, navigate to the navigation bar and
      select 'write'. Afterwards, you can now select your editor
      type; either the default custom editor or markdown.`,
    },
    {
      question: "How do I create a new event?",
      answer: `To create a new event, navigate to the navigation bar and
      select 'new event'. Afterwards, you can now select your event
      image, and fill in the form to satisfy your event
      outline and then click the create button to create your event.`,
    },
  ];

  return (
    <>
      <MetaData title="Help" />

      <HelpRenderer>
        <div
          className="help-main"
          style={{
            background: "linear-gradient(135deg, #f6f8f9 0%, #e5ebee 100%)",
          }}
        >
          <h1 className="help-h-txt">
            Help
            <IconHelp height="26" width="26" />
          </h1>
          <h2>Frequently Asked Questions</h2>
          <p className="h-des">
            Here are some common questions and answers that might address your
            concerns
          </p>
          <div className="h-accordion">
            {freQuestions.map((qI, i) => (
              <div key={i}>
                <input
                  type="radio"
                  name="accordion"
                  id={`accordion${i}`}
                  defaultChecked={qI?.ischecked}
                />
                <label htmlFor={`accordion${i}`} className="h-accordion-title">
                  » {qI.question}
                </label>
                <div className="h-accordion-content">{qI.answer}</div>
              </div>
            ))}
          </div>
        </div>
      </HelpRenderer>
      <Footer />
    </>
  );
};

export default Help;

const HelpRenderer = styled.div`
  min-height: 100vh;
  width: 100%;
  font-size: 13px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
    Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
  color: #000;
  display: flex;
  justify-content: center;
  padding: 3px 6px;
  .help-main {
    width: 70%;
    height: fit-content;
    background-color: white;
    border: 1px solid #ededed;
    border-radius: 8px;
    margin-top: 5px;
  }
  @media (max-width: 767px) {
    .help-main {
      width: 100%;
    }
    .h-accordion-title {
      font-size: 13px;
    }
  }
  .help-h-txt {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
      Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    padding: 5px 10px;
  }
  .h-des {
    font-size: 0.75rem;
    color: #8b8e98;
    font-weight: 600;
    padding: 5px 10px;
  }
  input[type="radio"] {
    display: none;
  }
  .h-accordion-title {
    display: block;
    padding: 5px 10px;
    border-bottom: 1px solid #ccc;
    color: #fff;
    background-color: #176984;
    z-index: 2;
    cursor: pointer;
    font-size: 14px;
  }

  .h-accordion-content {
    padding: 0;
    opacity: 0;
    max-height: 0;
    overflow: hidden;
    z-index: -1;
    transition: 0.3s linear;
    line-height: 1.5rem;
  }
  .h-accordion:last-child > .h-accordion-title,
  .h-accordion:last-child > .h-accordion-content {
    border: none;
  }
  h2 {
    padding: 5px 10px;
  }

  input:checked ~ .h-accordion-content {
    padding: 15px;
    opacity: 1;
    max-height: 500px;
    z-index: 1;
  }
`;
