const Facts = [
    {
      category: 'Science',
      facts: [
        "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
          "The human brain has a storage capacity equivalent to more than 2.5 petabytes (or a million gigabytes) of digital memory.",
          "The speed of light is approximately 299,792,458 meters per second (or about 186,282 miles per second).",
          "A single bolt of lightning carries enough energy to power a 60-watt light bulb for approximately six months.",
          "The average adult human body is made up of about 7 octillion (7 followed by 27 zeros) atoms.",
          "The first known vaccine was developed by Edward Jenner in 1796, who used cowpox to protect against smallpox.",
          "The largest volcano in the solar system is Olympus Mons on Mars. It stands about 13.6 miles (22 kilometers) high, which is nearly three times the height of Mount Everest.",
          "The total weight of all the ants on Earth is estimated to be roughly equal to the weight of all the humans on Earth.",
          "The shortest war in history lasted only 38 to 45 minutes. It was between Britain and Zanzibar in 1896.",
          "There are more trees on Earth than stars in the Milky Way galaxy."
        ],
    },
    {
      category: 'Technology',
      facts: [
        "The first computer mouse was made of wood and had only one button. It was invented by Doug Engelbart in 1964.",
          "The first commercial cell phone weighed about 2.2 pounds (1 kilogram) and was priced at approximately $3,995 when it was released in 1983.",
          "The first website ever created is still online. It was created by Tim Berners-Lee in 1991",
          "The first hard disk drive, developed by IBM in 1956, had a storage capacity of only 5 megabytes and was about the size of two refrigerators.",
          "The computer programming language Python is named after the British comedy group Monty Python.",
          "The first commercial video game console, the Magnavox Odyssey, was released in 1972 and had built-in games like Pong and Table Tennis.",
          "The first email was sent by Ray Tomlinson in 1971. The message was 'QWERTYUIOP,' which was simply a test of the system.",
          "The first mobile phone with a built-in camera was the J-SH04, released by Sharp in 2000. It had a resolution of 0.11 megapixels.",
          "The world's first 1 gigabyte hard disk drive was introduced by IBM in 1980. It weighed over 500 pounds (227 kilograms) and cost $40,000.",
          "The average smartphone today has more computing power than the computers used for the Apollo 11 moon landing."
        ],
    },
    {
      category: "Medicine",
    facts: [
        "Aspirin, one of the most commonly used medications, was derived from compounds found in willow bark.",
        "The human body produces about 25 million new cells each second.",
        "The placebo effect is a phenomenon in which a fake treatment or substance can sometimes produce real therapeutic effects due to the patient's belief in its efficacy.",
        "The human brain is the most energy-consuming organ in the body, accounting for about 20% of the body's total energy consumption.",
        "Alexander Fleming discovered penicillin, the world's first antibiotic, in 1928.",
        "The world's first successful organ transplant was performed in 1954 when a kidney was transplanted from one twin to another.",
        "The first successful heart transplant took place in 1967. Dr. Christiaan Barnard performed the surgery in Cape Town, South Africa.",
        "The longest recorded surgery lasted for 96 hours (4 days). It was performed in 2001 to separate conjoined twins.",
        "Human DNA, if unraveled and stretched, would reach a length of about 10 billion miles, which is enough to reach from Earth to Pluto and back.",
        "The field of genetics was revolutionized by the discovery of the structure of DNA by James Watson and Francis Crick in 1953.",
        "The first successful vaccine was developed by Edward Jenner to protect against smallpox in 1796.",
        "The world's first test-tube baby, Louise Brown, was born in 1978 through in vitro fertilization (IVF).",
        "X-rays were discovered accidentally by Wilhelm Roentgen in 1895.",
        "The human body has about 206 bones. The smallest bone is the stirrup bone (stapes) in the ear, while the femur is the longest and strongest bone.",
        "The discovery of insulin in 1921 revolutionized the treatment of diabetes.",
        "The first successful human-to-human blood transfusion was performed in 1818.",
        "The use of anesthesia in surgery was pioneered by an American dentist, William Morton, in 1846.",
        "The term 'virus' is derived from Latin and means 'poison' or 'slimy liquid.'",
        "The discovery of the structure and function of DNA led to the development of the field of genomics.",
        "The Human Genome Project, completed in 2003, sequenced and identified all the genes in human DNA.",
        "The field of pharmacogenomics studies how an individual's genetic makeup influences their response to medications.",
        "The human heart beats about 100,000 times per day, pumping around 2,000 gallons (7,600 liters) of blood.",
        "The first successful cesarean section (C-section) was performed in the 19th century, but the mother did not survive the procedure.",
        "The field of nanomedicine explores the use of nanotechnology for medical diagnosis, treatment, and prevention.",
        "The first successful chemotherapy treatment was introduced in the 1940s.",
        "The discovery of the structure of the double helix in DNA won James Watson and Francis Crick the Nobel Prize in Physiology or Medicine in 1962.",
        "The discovery of the antibiotic streptomycin by Selman Waksman in 1943 greatly advanced the treatment of tuberculosis.",
        "The concept of 'patient zero,' referring to the initial case of an epidemic or pandemic, originated during the investigation of the spread of HIV/AIDS.",
        "The discovery of the smallpox vaccine by Edward Jenner in 1796 marked a major breakthrough in medicine.",
      ],
      },
      {
        category: "Fashion",
        facts: [
          "Coco Chanel, the iconic fashion designer, popularized the little black dress (LBD) in the 1920s. It has since become a timeless fashion staple.",
          "High heels were originally worn by men. They were popularized in the 17th century by Persian soldiers and later became a symbol of status among European aristocracy.",
          "Denim jeans were invented by Levi Strauss in the 1870s as sturdy work pants for miners during the California Gold Rush.",
          "The fashion industry is one of the largest polluters in the world. It produces about 10% of global carbon emissions and is responsible for massive water consumption.",
          "The first fashion magazine, called 'Le Mercure Galant,' was published in France in the 17th century.",
          "The little black dress (LBD) gained further popularity when Audrey Hepburn wore a Givenchy LBD in the movie 'Breakfast at Tiffany's' in 1961.",
          "Fashion designer Diane von Furstenberg introduced the iconic wrap dress in the 1970s, which became a symbol of female empowerment and liberation.",
          "The bikini, one of the most popular swimwear styles, was introduced by French designer Louis Réard in 1946.",
          "The red carpet tradition at awards shows originated in ancient Greece, where red-dyed textiles were used to honor gods and goddesses.",
          "In the 19th century, women's fashion was so restrictive that some dresses required the assistance of multiple people to put on.",
          "The concept of fashion weeks, where designers showcase their latest collections, originated in Paris in the mid-19th century.",
          "The iconic Burberry trench coat was developed as a military garment during World War I and later became a fashion staple.",
          "The first fashion designer to launch a luxury brand was Charles Frederick Worth in the 19th century.",
          "The term 'haute couture' refers to high-end fashion that is custom-made and created by hand. It is protected by French law and can only be used by designated fashion houses.",
          "The little blue box from Tiffany & Co., known as the Tiffany Blue Box, has become an iconic symbol of luxury and exclusivity.",
          "The concept of 'fast fashion,' where clothing is produced quickly and inexpensively, gained popularity in the 1990s but has faced criticism for its environmental and ethical impact.",
          "The invention of the sewing machine by Elias Howe in 1846 revolutionized the fashion industry by allowing mass production of clothing.",
          "The fashion industry has been increasingly embracing diversity and inclusivity, with more representation of models of different races, body types, and genders.",
          "The concept of fashion trends emerged in the 20th century, influenced by cultural shifts, social movements, and influential figures.",
          "Fashion designer Gabrielle 'Coco' Chanel is credited with popularizing pants for women in the early 20th century, challenging traditional gender norms."
        ]
      },
      {
        category: 'Health Tips',
        facts:  [
          "Drink plenty of water throughout the day to stay hydrated and promote overall health.",
          "Eat a balanced diet that includes a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats.",
          "Engage in regular physical activity to improve cardiovascular health, build strength, and maintain a healthy weight.",
          "Get enough sleep each night to support proper functioning of the body and promote overall well-being.",
          "Practice good hand hygiene by washing your hands regularly with soap and water or using hand sanitizer.",
          "Maintain a regular exercise routine that includes both cardiovascular exercises and strength training.",
          "Limit processed foods, sugary drinks, and excessive consumption of salt to promote a healthy diet.",
          "Incorporate mindfulness techniques, such as meditation or deep breathing exercises, into your daily routine to reduce stress.",
          "Practice proper posture to prevent back and neck pain. Sit and stand with your shoulders back and spine aligned.",
          "Wear sunscreen with a high SPF to protect your skin from harmful UV rays and reduce the risk of skin cancer.",
          "Avoid smoking and limit alcohol consumption to reduce the risk of various health conditions.",
          "Take breaks from prolonged sitting or desk work. Stretch and move around to improve circulation and prevent stiffness.",
          "Practice proper oral hygiene by brushing your teeth twice a day and flossing regularly.",
          "Stay socially connected with friends and loved ones to support mental and emotional well-being.",
          "Limit screen time and take regular breaks from electronic devices to protect your eyes and reduce digital fatigue.",
          "Schedule regular check-ups and screenings with your healthcare provider to detect and prevent health issues early.",
          "Practice safe sex by using condoms and getting tested regularly for sexually transmitted infections (STIs).",
          "Manage stress through healthy coping mechanisms, such as exercise, hobbies, or seeking support from loved ones.",
          "Limit caffeine intake and opt for herbal teas or decaffeinated alternatives for better sleep quality.",
          "Listen to your body's signals and prioritize self-care. Rest when needed and give yourself permission to take breaks."
        ] 
        
      }
  ];

  export default Facts
  