export const NEW_ARTICLE_REQUEST = "NEW_ARTICLE_REQUEST";
export const NEW_ARTICLE_SUCCESS = "NEW_ARTICLE_SUCCESS";
export const NEW_ARTICLE_RESET = "NEW_ARTICLE_RESET";
export const NEW_ARTICLE_FAIL = "NEW_ARTICLE_FAIL";

export const LIKE_UNLIKE_ARTICLE_REQUEST = "LIKE_UNLIKE_ARTICLE_REQUEST";
export const LIKE_UNLIKE_ARTICLE_SUCCESS = "LIKE_UNLIKE_ARTICLE_SUCCESS";
export const LIKE_UNLIKE_ARTICLE_RESET = "LIKE_UNLIKE_ARTICLE_RESET";
export const LIKE_UNLIKE_ARTICLE_FAIL = "LIKE_UNLIKE_ARTICLE_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const SAVE_UNSAVE_ARTICLE_REQUEST = "SAVE_UNSAVE_ARTICLE_REQUEST";
export const SAVE_UNSAVE_ARTICLE_SUCCESS = "SAVE_UNSAVE_ARTICLE_SUCCESS";
export const SAVE_UNSAVE_ARTICLE_RESET = "SAVE_UNSAVE_ARTICLE_RESET";
export const SAVE_UNSAVE_ARTICLE_FAIL = "SAVE_UNSAVE_ARTICLE_FAIL";

export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_RESET = "DELETE_ARTICLE_RESET";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_RESET = "ARTICLE_DETAILS_RESET";
export const ARTICLE_DETAILS_FAIL = "ARTICLE_DETAILS_FAIL";

export const NEW_COMMENT_REPLY_REQUEST = "NEW_COMMENT_REPLY_REQUEST";
export const NEW_COMMENT_REPLY_SUCCESS = "NEW_COMMENT_REPLY_SUCCESS";
export const NEW_COMMENT_REPLY_RESET = "NEW_COMMENT_REPLY_RESET ";
export const NEW_COMMENT_REPLY_FAIL = "NEW_COMMENT_REPLY_FAIL";

export const ARTICLE_SEARCH_REQUEST = "ARTICLE_SEARCH_REQUEST";
export const ARTICLE_SEARCH_SUCCESS = "ARTICLE_SEARCH_SUCCES";
export const ARTICLE_SEARCH_FAIL = "ARTICLE_SEARCH_FAIL";
export const ARTICLE_SEARCH_RESET = "ARTICLE_SEARCH_RESET";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";
export const UPDATE_ARTICLE_RESET = "UPDATE_ARTICLE_RESET";

export const DELETE_REPLY_FAIL = " DELETE_REPLY_FAIL";
export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_RESET = "DELETE_REPLY_RESET";

export const DELETE_COMMENT_FAIL = " DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_SUCCESS = " DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_REQUEST = " DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
