export const NEW_EVENT_REQUEST = "NEW_EVENT_REQUEST";
export const NEW_EVENT_SUCCESS = "NEW_EVENT_SUCCESS";
export const NEW_EVENT_RESET = "NEW_EVENT_RESET";
export const NEW_EVENT_FAIL = "NEW_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_RESET = "EVENT_DETAILS_RESET";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";

export const EVENT_SEARCH_REQUEST = "EVENT_SEARCH_REQUEST";
export const EVENT_SEARCH_SUCCESS = "EVENT_SEARCH_SUCCES";
export const EVENT_SEARCH_FAIL = "EVENT_SEARCH_FAIL";
export const EVENT_SEARCH_RESET = "EVENT_SEARCH_RESET";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
