export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS'
export const MARK_NOTIFICATION_UNREAD = 'MARK_NOTIFICATION_UNREAD'
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS'
export const MARK_ALL_NOTIFICATION_READ = 'MARK_ALL_NOTIFICATION_READ'