export const NEW_PAST_QUESTION_REQUEST = "NEW_PAST_QUESTION_REQUEST";
export const NEW_PAST_QUESTION_SUCCESS = "NEW_PAST_QUESTION_SUCCESS";
export const NEW_PAST_QUESTION_RESET = "NEW_PAST_QUESTION_RESET";
export const NEW_PAST_QUESTION_FAIL = "NEW_PAST_QUESTION_FAIL";

export const DELETE_PAST_QUESTION_REQUEST = "DELETE_PAST_QUESTION_REQUEST";
export const DELETE_PAST_QUESTION_SUCCESS = "DELETE_PAST_QUESTION_SUCCESS";
export const DELETE_PAST_QUESTION_RESET = "DELETE_PAST_QUESTION_RESET";
export const DELETE_PAST_QUESTION_FAIL = "DELETE_PAST_QUESTION_FAIL";

export const PAST_QUESTION_DETAILS_REQUEST = "PAST_QUESTION_DETAILS_REQUEST";
export const PAST_QUESTION_DETAILS_SUCCESS = "PAST_QUESTION_DETAILS_SUCCESS";
export const PAST_QUESTION_DETAILS_RESET = "PAST_QUESTION_DETAILS_RESET";
export const PAST_QUESTION_DETAILS_FAIL = "PAST_QUESTION_DETAILS_FAIL";

export const PAST_QUESTION_SEARCH_REQUEST = "PAST_QUESTION_SEARCH_REQUEST"
export const PAST_QUESTION_SEARCH_SUCCESS = "PAST_QUESTION_SEARCH_SUCCESS"
export const PAST_QUESTION_SEARCH_FAIL = "PAST_QUESTION_SEARCH_FAIL"
export const PAST_QUESTION_SEARCH_RESET = "export const PAST_QUESTION_SEARCH_RESET"

 export const PAST_QUESTION_DOWNLOAD_FAIL = 'PAST_QUESTION_DOWNLOAD_FAIL';
 export const PAST_QUESTION_DOWNLOAD_SUCCESS = 'PAST_QUESTION_DOWNLOAD_SUCCESS';
 export const PAST_QUESTION_DOWNLOAD_REQUEST = 'PAST_QUESTION_DOWNLOAD_REQUEST';
 export const PAST_QUESTION_DOWNLOAD_RESET = 'PAST_QUESTION_DOWNLOAD_RESET';

export const CLEAR_ERRORS = "CLEAR_ERRORS";