export const NEW_SUBSCRIPTION_REQUEST = "NEW_SUBSCRIPTION_REQUEST";
export const NEW_SUBSCRIPTION_SUCCESS = "NEW_SUBSCRIPTION_SUCCESS";
export const NEW_SUBSCRIPTION_RESET = "NEW_SUBSCRIPTION_RESET";
export const NEW_SUBSCRIPTION_FAIL = "NEW_SUBSCRIPTION_FAIL";

export const SUBSCRIPTION_DETAILS_REQUEST = "SUBSCRIPTION_DETAILS_REQUEST";
export const SUBSCRIPTION_DETAILS_SUCCESS = "SUBSCRIPTION_DETAILS_SUCCESS";
export const SUBSCRIPTION_DETAILS_RESET = "SUBSCRIPTION_DETAILS_RESET";
export const SUBSCRIPTION_DETAILS_FAIL = "SUBSCRIPTION_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";